controller:
  service:
    type: LoadBalancer
    ports:
      http: 8080
      https: 8443
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  admissionWebhooks:
    enabled: true
  metrics:
    enabled: true
  ingressClassResource:
    name: "nginx"
    enabled: true
